name: Test

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/cobertura-coverage.xml
