name: Test

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/cobertura-coverage.xml

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Validate build
        shell: bash
        run: |
          set -e
          npm ci
          git add -A
          npm run package
          if [ -n "$(git status --porcelain -- dist)" ]; then
            echo "::error::Build result differs. Run 'npm run package' then commit and push any changes"
            git status --porcelain -- dist
            exit 1
          fi
